rebase to alpine 3.20
linuxserver/docker-fail2ban pull request #29
Opened 2024-10-12 13:50 UTC by drizuid

rebase to alpine 3.20

2024-10-12 23:51 UTC, drizuid commented
pending test by xe

2024-10-15 11:43 UTC, drizuid commented
tested and confirmed by xe - https://discord.com/channels/354974912613449730/512708069709316137/1295692294200098826

2024-10-15 12:50 UTC, thespad requested changes
Please add the build_version output to the Dockerfiles as per https://github.com/linuxserver/docker-sabnzbd/blob/master/Dockerfile#L66

2024-10-15 14:03 UTC, thespad approved these changes

2024-10-15 14:04 UTC, merged